name: 📚 Documentation
description: Report an issue related to https://pypose.org/docs

body:
- type: textarea
  attributes:
    label: 📚 The doc issue
    description: >
      A clear and concise description of what content in https://pypose.org/docs is an issue.
      If this has to do with the general https://pypose.org website, please file an issue at
      https://github.com/pypose/pypose.github.io/issues instead. If this has to
      do with https://pypose.org/tutorials, please file an issue at
      https://github.com/pypose/tutorials/issues/new.
  validations:
    required: true
- type: textarea
  attributes:
    label: Suggest a potential alternative/fix
    description: >
      Tell us how we could improve the documentation in this regard.
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
